name: Sendtiment
favicon: null
layout_spectrum: 0.33614
typography_spectrum: 0.5859
title: Sendtiment
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dd6f77'
    - '#896274'
    - '#accfd3'
    - '#f9b3a8'
    - '#765464'
  brandStrength: 0.25
  lightness: 0.214474092470482
  saturation: 0.875
  rhythmicContrast: 0.8408889130223542
purpose: []
