name: Sendtiment
favicon: null
layout_spectrum: 0
typography_spectrum: 0.62559
title: Sendtiment
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dd6f77'
    - '#896274'
    - '#accfd3'
    - '#f9b3a8'
    - '#765464'
  brandStrength: 0.375
  lightness: 0.4375
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
